deafault: &default
  adapter: mongoose
  options:
    db:
      native_parser: true
    server:
      poolSize: 5

production:
  <<: *default
  uri: {{ process.env.MONGODB_URI }}


development:
  <<: *default
  uri: mongodb://localhost/
  name: ongonovodia_dev

test:
  <<: *default
  uri: mongodb://localhost/
  name: ongonovodia_test
